### ISSUE TITLE
Minor derivatives optimisations: Fits 1.2.0

### ISSUE THREAD

**Issue by DiegoPino** [Islandora-Collaboration-Group/ISLE#96] opened 2018-01-25 18:49 UTC
Hi,

# ISSUE 
One the issues with current FITS (1.2.0) it that it during the TECHMD generation Apache Tika is executed on Binaries resulting in huge/large amount of temporary file(s), much larger than original datastreams that are checked againts. This can lead, on large ingest sets to temporary out of space situations. Normal /tmp cleanup routines found on Ubuntu are not able to deal with this files.

Filenames start with apache-tika

The simples fix is to comment this line

at  `/usr/local/fits-1.2.0/xml/fits.xml`
```XML
<!--  Comment tika processing or your /tmp file will fill up sooo fast!
          <tool class="edu.harvard.hul.ois.fits.tools.tika.TikaTool" exclude-exts="jar,avi,mov,mpg,mpeg,mkv,mp4,mpeg4,m2ts,mxf,ogv,mj2,divx,dv,m4v$
 -->
````
This has issue has been replicated by Samvera users/DGI and Metro (all with different levels of frustration) 

Omit the warning message at will.

# HOW TO REPLICATE

Execute any derivative regeneration on Objects where TECHMD processing is enabled. Look at your /tmp folder for apache-tika files.

**Comment by patdunlavey** [comment] 2018-02-06 17:51
Is there a reason it would not make sense to modify the line to use "include-exts=..." where we only list extensions for a few basic mimetypes?

**Comment by DiegoPino** [comment] 2018-02-06 17:53
true, that would also help/be a solution. I was just thinking about saving the day (i filled 500 Gbytes in a day without this change)

**Comment by g7morris** [comment] 2019-03-27 19:31
https://github.com/Islandora-Collaboration-Group/ISLE/issues/206 is a duplicate of this original ticket. It does have more server side information but the solution proposed within it is not as good as this.

**Comment by shauntru** [comment] 2019-05-14 13:50
I finally had a chance to review what happens when you turn off Tika during derivative generation. I then compared the resultant TECHMD against the same file with Tika turned on during derivative generation. Not surprisingly, there are no differences for filetypes other than PDF. In the case of PDF, the only difference I saw between Tika being on/off is a single line declaring the version of Tika being used. With that confirmation (that Tika isn't doing much of anything), I recommend commenting out the Tika tool line, as Diego originally suggested. I'm going to put in a pull request for this.

**Comment by g7morris** [comment] 2019-05-14 17:16
@shauntru Even for OCR generation? I'm surprised as this issue seems to occur a lot for me when ingesting files i.e. newspapers, books (using internet archive book viewer) etc. Sooo I think TIKA is doing a lot frankly otherwise where are the fragments coming from?

**Comment by shauntru** [comment] 2019-05-14 19:56
@g7morris I dug into this a little bit more and it looks like TIKA gives some info about the tool used to generate OCR, but not much else *that I've seen*. I've tested against a couple dozen files. My point is that I don't see much value added by the data that TIKA does create. I have no idea what is inside those fragments.

**Comment by shauntru** [comment] 2019-05-14 19:58
@g7morris Another question for you - has there been improvements to /tmp garbage collection on ISLE? In the course of testing the fix for this issue, I've found that the /tmp folder is trashing TIKA fragments on its own. While running IMI and monitoring the /tmp folder, I'm seeing the fragments appear and then promptly go away. By the end of the ingest they are all gone. So my question is has something changed and is this fix still necessary if so?

**Comment by g7morris** [comment] 2019-05-14 22:11
@shauntru I think the fix is still necessary. I've had to setup cronjobs on other ISLE setups to zap all involved /tmp directories so I'm not seeing what you're describing. Perhaps when they are small batches? How about if the ingest is over 1 -2 days? ;) That is typically where I see the trouble occur. 

From my experience it appears that rhe fragments are from the OCR process specifically objects / derived text areas that TIKA / OCR had "trouble" with and is "pointing out" this area within the fragment itself. I think the fragments are created ultimately as a nice helpful thing for a human to review and correct. In this context, with a large ingest or ingests over time, this "nice thing" becomes a server / disk killer in disguise. If someone needs it, they can read how to turn it on, right?

**Comment by shauntru** [comment] 2019-05-14 23:15
@g7morris That's right! You had explained the contents of the TIKA fragments to me earlier. 
And I kind of suspected that the cleanup I was seeing was due to the small size ingest. Thanks for the sanity check. Will make a PR asap.

**Comment by bseeger** [comment] 2019-06-27 15:45
Should be solved by https://github.com/Islandora-Collaboration-Group/isle-apache/pull/5

**Closed by bseeger** 2019-06-27 15:45 UTC
Labels: ISLE-APACHE, ISLE-v.1.1.2
