### ISSUE TITLE
Djatoka setting in OpenSeadragon

### ISSUE THREAD

**Issue by petermacdonald** [Islandora-Collaboration-Group/ISLE#76] opened 2017-12-11 14:14 UTC
Djatoka is not configured properly in ISLE. This prevents the Large Images from displaying using OpenSeadragon.

That is, if one is configuring the OpenSeadragon viewer and sets the "Image Server" to "Adore-Djatoka Image Server" the location of the "Djatoka-Adore Imager Server Settings" should be this:

http://fedora:8080/adore-djatoka/resolver

not just "adore-djatoka/resolver"

![image](https://user-images.githubusercontent.com/693785/33834911-ae22f6aa-de52-11e7-94f2-114e8dcb496a.png)

Peter

**Comment by g7morris** [comment] 2017-12-11 15:23
Hi @petermacdonald 

I'm not sure why you're expericing this as an issue. 

Within the `install_site.sh` is a Drush vset for this variable:
```
/usr/local/bin/drush -u 1 -y vset --format=json islandora_openseadragon_settings '{"debugMode":0,"djatokaServerBaseURL":"http:\/\/apache\/adore-djatoka\/resolver","animationTime":"1.5","blendTime":"0.1","alwaysBlend":0,"autoHideControls":1,"immediateRender":0,"wrapHorizontal":0,"wrapVertical":0,"wrapOverlays":0,"panHorizontal":1,"panVertical":1,"showNavigator":1,"minZoomImageRatio":"0.8","maxZoomPixelRatio":"2","visibilityRatio":"0.5","springStiffness":"5.0","imageLoaderLimit":"5","clickTimeThreshold":"300","clickDistThreshold":"5","zoomPerClick":"2.0","zoomPerScroll":"1.2","zoomPerSecond":"2.0"}'
```

In this instance, the setting for this should be: `http://apache/adore-djatoka/resolver`

Can you confirm?

**Comment by hamhpc** [comment] 2017-12-11 15:37
I'm going to re-OS my second test box with the latest updates and have Peter try that out so we can report back and see where this issue is and report on it better.

**Comment by g7morris** [comment] 2017-12-11 16:17
Hi @petermacdonald & @hamhpc , 

Just want to note that I've re-tested the settings on our test build platform and I'm unable to reproduce the error. 

```
ADORE DJATOKA IMAGE SERVER SETTINGS
Settings for Adore-Djatoka Image Server

adore-djatoka/resolver

Successfully connected to Adore Djatoka Server.
``
Drush vset is:
```
/usr/local/bin/drush -u 1 -y vset --format=json islandora_openseadragon_settings '{"debugMode":0,"djatokaServerBaseURL":"http:\/\/apache\/adore-djatoka\/resolver","animationTime":"1.5","blendTime":"0.1","alwaysBlend":0,"autoHideControls":1,"immediateRender":0,"wrapHorizontal":0,"wrapVertical":0,"wrapOverlays":0,"panHorizontal":1,"panVertical":1,"showNavigator":1,"minZoomImageRatio":"0.8","maxZoomPixelRatio":"2","visibilityRatio":"0.5","springStiffness":"5.0","imageLoaderLimit":"5","clickTimeThreshold":"300","clickDistThreshold":"5","zoomPerClick":"2.0","zoomPerScroll":"1.2","zoomPerSecond":"2.0"}'
```

**Comment by hamhpc** [comment] 2017-12-11 19:08
We tried this and it is indeed working properly. I think it might be that it just looks funny compared to what we're used to seeing at our institution but to confirm we're now seeing "adore-djatoka/resolver" as the entry and it does work properly. This can be closed as well.

**Closed by hamhpc** 2017-12-11 19:08 UTC
