### ISSUE TITLE
Islandora user UID

### ISSUE THREAD

**Issue by marksandford** [Islandora-Collaboration-Group/ISLE#233] opened 2018-11-09 16:57 UTC
https://github.com/Islandora-Collaboration-Group/ISLE/issues/187

**Comment by dwk2** [comment] 2021-03-11 18:11
Closing this issue. It is a duplicate of the still open https://github.com/Islandora-Collaboration-Group/ISLE/issues/187

**Closed by dwk2** 2021-03-11 18:11 UTC
Labels: Documentation
