### ISSUE TITLE
Upgrading MySQL tables to utf8mb4 may be required

### ISSUE THREAD

**Issue by marksandford** [Islandora-Collaboration-Group/ISLE#236] opened 2018-11-09 16:54 UTC
https://github.com/Islandora-Collaboration-Group/ISLE/issues/189

**Comment by g7morris** [comment] 2021-03-10 18:28
Duplicate of https://github.com/Islandora-Collaboration-Group/ISLE/issues/189 will be handled by script and README. This developer will update Documentation of necessary steps. Closing dupe

**Closed by g7morris** 2021-03-10 18:28 UTC
Labels: Documentation
